baseURL = "https://www.elizabeth-hewett.com"
languageCode = "en-us"
title = "Elizabeth Hewett"
theme = "personal-web"
copyright="© Elizabeth Hewett"
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm Elizabeth"
  sub = "CAD Designer and Drafter"

[params.main]
  latestPublishHeader = "My Latest Project"

[taxonomies]
  design = "designs"
  tech = "techs"

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio']

[params.notFound]
  wrench = "/images/wrench.png"
  h1 = 'Ooops!'
  p = "It seems that this page doesn't exist."

[params.sections]
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '/images/sidebar.jpg'
   logo = '/images/elizabeth-hewett.jpg'

[params.assets]
  favicon = "/images/favicon.png"
  customCSS = ""

[params.social]
    linkedin = "https://www.linkedin.com/in/elizabeth-hewett-078b0692/"

[params.contact]
  email = "eliz.hewett@gmail.com"
  text = "Email me"

[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "post"
  name = "Post"
  title = "Post"
  url = "/post/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]

  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true